apiVersion: v1
kind: Secret
metadata:
  name: guacamole-secrets
  namespace: guacamole
type: Opaque
data:
  postgres-password: Z3VhY2Ftb2xlX3Bhc3N3b3Jk  # base64: guacamole_password
  postgres-user: Z3VhY2Ftb2xlX3VzZXI=          # base64: guacamole_user